spring:
  datasource:
    druid:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://127.0.0.1:5432/test
      username: postgres
      password: postgres
mybatis-plus:
  type-aliases-package: com.wu.demo.admin
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    cache-enabled: true
    auto-mapping-behavior: FULL
    default-executor-type: REUSE
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
logging:
  path: d:\test\log\admin-back-demo